version: "3.3"
services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: api.dockerfile
    environment:
      JWT: key
      PORT: 8080
      MONGO_URL: mongodb://
    ports: 
      - "8080:8080"
     

 



